// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWGA06UvN0HQkMpAopNg8K20RQwmzJkKA',
    appId: '1:421680960621:android:877db939f8b81ff544db64',
    messagingSenderId: '421680960621',
    projectId: 'capstone-f748a',
    storageBucket: 'capstone-f748a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9zuns8lNmKkXuR28Oq-UULILb7RUwnqg',
    appId: '1:421680960621:ios:9dd7b493295ac0ff44db64',
    messagingSenderId: '421680960621',
    projectId: 'capstone-f748a',
    storageBucket: 'capstone-f748a.appspot.com',
    iosClientId: '421680960621-b02p5vt5t370ja1epcpo5mrk5nvt14pj.apps.googleusercontent.com',
    iosBundleId: 'com.capstone.capstone1',
  );
}
